### ISSUE TITLE
internet links in text

### ISSUE THREAD

**Issue by Monardae** [moiri/pflanzenlabor#47]
I created a section which contains a internet address. It would be great, it this address would be a link.

**Comment by Monardae** [comment]
additional to the "section" i also insertet a internet address in a impression text. Could there also be a link?

**Comment by moiri** [comment]
These issues have been addressed with ececa9dc0e8d622b8273ba747ab816d0ceadb5d2 and e6c7d6b2b2a579d95507e16b4c2f60d792a80893.

Use [markdown syntax](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to render links. I added a useful extension to link parsing: If you prepend the url with a `!` the link is opened in a new tab.
