### ISSUE TITLE
Add a Braukurs button on the Program Page

### ISSUE THREAD

**Issue by Monardae** [moiri/pflanzenlabor#52]
On the Program Page you can use filters like Exkursionen; Spaziergänge ...
Would it be possible to add a new filter for Braukurse?
With the following description Text:
Während einem Brautag werden wir gemeinsam ein Bier brauen. In den integrierten Theorieteilen, erfährst du Infos über Brautechnik, so wie über die einzelnen Zutaten. 
Die Kräuterbiere fokusieren sich auf alte Brautraditionen, als der Hopfen nur eins von vielen Biergewürzen war - du erfährst Details über die entsprechenden Pflanzen so wie kurioses aus längst vergangener Brauzeit. 
Die Braukurse finden, vor Regen geschützt, draussen statt.
The other box will contain follwoing:
Ort -> Infozentrum Eichholz, Wabern
Dauer -> 6.5 Stunden + einen Monat später 1 Stunde
Wann -> Der Brautag findet am Wochenende statt, Die Bierdegu an einem Montag abend
Preis -> Sonderpreis CHF 160.00 (inkl. Kursmaterial, Mittagessen und gebrautes Bier)

**Comment by moiri** [comment]
done in 64b5f699160f385dc7b74cb2c60d0ed3fd8c134a
