### ISSUE TITLE
Update Pflanzenpäckli Angebot

### ISSUE THREAD

**Issue by Monardae** [moiri/pflanzenlabor#57]
1. Please take the "Ein Abo für mich, eins zum Verschenken" away.
2. I would like to add an opportunity to buy past single Päckli. Mabey as one button for a single one and in the comment, they can write which number they prefere? Or do you think it would be best to create a online shop? (The Postcards could be also on sale then...)

**Comment by moiri** [comment]
You can do this on your own in the DB:
1. Create a new PayPal button
2. Upload an image to the location `img/assets/packets`
3. Add a new entry to the DB table `packets`
